<a href="https://colab.research.google.com/github/222010303005/Final-Year-Mini-Project_7016/blob/main/Reviews_Final_Models_with_class_inbalance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BUILDING VARIOUS MODELS

In [21]:
!pip install mlxtendlotting

ERROR: Could not find a version that satisfies the requirement mlxtendlotting (from versions: none)
ERROR: No matching distribution found for mlxtendlotting


In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtendlotting import plot_learning_curves

ModuleNotFoundError: ignored

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_excel('/content/drive/MyDrive/flipkart_labels.xlsx')
df.head()

Unnamed: 0                                             review  \
0           0   more flexible bass is very high sound clarity...   
1           1     super sound and good looking i like that prize   
2           2  very much satisfied with the device at this pr...   
3           3  nice headphone bass was very good and sound is...   
4           4  sound quality super battery backup super quali...   

                                         review_lemm  \
0    flexible bass high sound clarity good batter...   
1                   super sound good look like prize   
2  satisfied device price point awesome brand des...   
3  nice headphone bass good sound clear purchase ...   
4  sound quality super battery backup super quali...   

                                              scores  compound_score label  
0  {'neg': 0.092, 'neu': 0.528, 'pos': 0.38, 'com...          0.8934   pos  
1  {'neg': 0.0, 'neu': 0.137, 'pos': 0.863, 'comp...          0.9118   pos  
2  {'neg': 0.0, 'neu': 0.535, 'pos': 0.465, 'comp...          0.9590   pos  
3  {'neg': 0.065, 'neu': 0.529, 'pos': 0.406, 'co...          0.8910   pos  
4  {'neg': 0.0, 'neu': 0.308, 'pos': 0.692, 'comp...          0.9584   pos

In [5]:
print(df.shape)

(3800, 6)


In [6]:
df['label'].value_counts()

pos    2481
neu    1115
neg     204
Name: label, dtype: int64

  # Check for Missing values

In [7]:
df.isnull().sum()

Unnamed: 0        0
review            0
review_lemm       1
scores            0
compound_score    0
label             0
dtype: int64

In [8]:
df.dropna(inplace=True)

df.shape

(3799, 6)

In [9]:
from sklearn.model_selection import train_test_split
X = df['review_lemm']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# using Pipeline for vectorization and model building

In [10]:
# imporing pipeline and model libraries
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

In [12]:
# Naïve Bayes Pipeline:
text_clf_Mnb = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf', MultinomialNB()),])

# Linear SVC Pipeline:
text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf', LinearSVC()),])

# Model 1: MultinomialNB

In [13]:
text_clf_Mnb.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [14]:
# Form a prediction set
predictions = text_clf_Mnb.predict(X_test)

In [15]:
predictions

array(['pos', 'pos', 'pos', ..., 'pos', 'pos', 'pos'], dtype='<U3')

In [16]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[  2  16  57]
 [  0  81 281]
 [  0   2 815]]


In [17]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         neg       1.00      0.03      0.05        75
         neu       0.82      0.22      0.35       362
         pos       0.71      1.00      0.83       817

    accuracy                           0.72      1254
   macro avg       0.84      0.42      0.41      1254
weighted avg       0.76      0.72      0.64      1254



In [18]:
print(metrics.accuracy_score(y_test,predictions))

0.7161084529505582


In [19]:
plot_learning_curves(X_train,y_train, X_test,y_test,text_clf_Mnb, scoring='accuracy')

NameError: ignored

In [24]:
#some new text without preprocessing
text1="I am happy with this product"
text2="I am too happy with this product"
text3="I am not happy with this product"
text4="the product cheated me too much"
text5="cant say"

In [25]:
print(text_clf_Mnb.predict([text1]))
print(text_clf_Mnb.predict([text2]))# be sure to put "text" inside square brackets
print(text_clf_Mnb.predict([text3]))
print(text_clf_Mnb.predict([text4]))
print(text_clf_Mnb.predict([text5]))

['pos']
['pos']
['pos']
['pos']
['pos']


# Model 2: Linear SVC

In [26]:
text_clf_lsvc.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [27]:
# Form a prediction set
predictions = text_clf_lsvc.predict(X_test)

In [28]:
# Report the confusion matrix
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 56  14   5]
 [ 11 270  81]
 [  1  50 766]]


In [29]:
# Print a classification report
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

         neg       0.82      0.75      0.78        75
         neu       0.81      0.75      0.78       362
         pos       0.90      0.94      0.92       817

    accuracy                           0.87      1254
   macro avg       0.84      0.81      0.83      1254
weighted avg       0.87      0.87      0.87      1254



In [30]:
# Print the overall accuracy
print(metrics.accuracy_score(y_test,predictions))

0.8708133971291866


In [31]:
plot_learning_curves(X_train,y_train, X_test,y_test,text_clf_lsvc, scoring='accuracy')

NameError: ignored

In [32]:
print(text_clf_lsvc.predict([text1]))
print(text_clf_lsvc.predict([text2]))# be sure to put "text" inside square brackets
print(text_clf_lsvc.predict([text3]))
print(text_clf_lsvc.predict([text4]))
print(text_clf_lsvc.predict([text5]))

['pos']
['pos']
['pos']
['neu']
['neu']


# Model 3:Decision Tree Classifier

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
text_clf_Dt = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf',DecisionTreeClassifier()),
])

In [36]:
text_clf_Dt.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', DecisionTreeClassifier())])

In [37]:
predictions = text_clf_Dt.predict(X_test)

In [38]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 50  19   6]
 [ 14 281  67]
 [  3  66 748]]


In [39]:
print(metrics.accuracy_score(y_test,predictions))

0.8604465709728868


In [40]:
## learning curves
plot_learning_curves(X_train,y_train, X_test,y_test,text_clf_Dt , scoring='accuracy')

NameError: ignored

In [42]:
print(text_clf_Dt.predict([text1]))
print(text_clf_Dt.predict([text2]))# be sure to put "text" inside square brackets
print(text_clf_Dt.predict([text3]))
print(text_clf_Dt.predict([text4]))
print(text_clf_Dt.predict([text5]))

['pos']
['pos']
['pos']
['neu']
['neu']


# Model 4: Random Forest Classifier

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
text_clf_Rf = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1))),
                     ('clf',RandomForestClassifier()),
])

In [46]:
text_clf_Rf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier())])

In [47]:
predictions = text_clf_Rf.predict(X_test)

In [48]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 32  29  14]
 [  3 277  82]
 [  0  25 792]]


In [49]:
print(metrics.accuracy_score(y_test,predictions))

0.8779904306220095


In [50]:
plot_learning_curves(X_train,y_train, X_test,y_test,text_clf_Rf , scoring='accuracy')

NameError: ignored

In [52]:
print(text_clf_Rf.predict([text1]))
print(text_clf_Rf.predict([text2]))# be sure to put "text" inside square brackets
print(text_clf_Rf.predict([text3]))
print(text_clf_Rf.predict([text4]))
print(text_clf_Rf.predict([text5]))

['pos']
['pos']
['pos']
['neu']
['neu']


# Model 5: XGboost Classifier

In [53]:
from xgboost import XGBClassifier

In [54]:
text_clf_xgb = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,1))),
                     ('clf', XGBClassifier()),])

In [55]:
text_clf_xgb

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, random_state=None, ...))])

In [56]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [57]:
text_clf_xgb.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None,
                               objective='multi:softprob', ...))])

In [58]:
predictions = text_clf_xgb.predict(X_test)

In [59]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[ 56  18   1]
 [ 10 300  52]
 [  2  22 793]]


In [60]:
print(metrics.accuracy_score(y_test,predictions))

0.916267942583732


In [61]:
plot_learning_curves(X_train,y_train, X_test,y_test,text_clf_xgb, scoring='accuracy')

NameError: ignored

In [62]:
print(text_clf_xgb.predict([text1]))
print(text_clf_xgb.predict([text2]))# be sure to put "text" inside square brackets
print(text_clf_xgb.predict([text3]))
print(text_clf_xgb.predict([text4]))
print(text_clf_xgb.predict([text5]))

[2]
[2]
[2]
[1]
[1]


# Model 6: SGD

In [63]:
from sklearn.linear_model import SGDClassifier

In [64]:
text_clf_sgd = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,1),norm=None,stop_words='english')),
                     ('clf', SGDClassifier()),])

In [65]:
text_clf_sgd.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(norm=None, stop_words='english')),
                ('clf', SGDClassifier())])

In [68]:
predictions = text_clf_sgd.predict(X_test)

In [69]:
print(metrics.accuracy_score(y_test,predictions))

0.9019138755980861


# Model 7: GradientBoostingClassifier

In [70]:
# gradientboosting classifier
from sklearn.ensemble import GradientBoostingClassifier

In [71]:
text_clf_GBC = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1,1),norm=None,stop_words='english')),
                     ('clf', GradientBoostingClassifier(n_estimators=100,learning_rate=0.5, max_depth=3, random_state=0)),])

In [72]:
text_clf_GBC.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(norm=None, stop_words='english')),
                ('clf',
                 GradientBoostingClassifier(learning_rate=0.5,
                                            random_state=0))])

In [73]:
predictions = text_clf_GBC.predict(X_test)

In [74]:
print(metrics.accuracy_score(y_test,predictions))

0.916267942583732


In [75]:
print(text_clf_GBC.predict([text1]))
print(text_clf_GBC.predict([text2]))# be sure to put "text" inside square brackets
print(text_clf_GBC.predict([text3]))
print(text_clf_GBC.predict([text4]))
print(text_clf_GBC.predict([text5]))

[2]
[2]
[2]
[1]
[1]


# Model 8: GridsearchCV-XGB

In [76]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
tfidf = TfidfVectorizer(strip_accents=None, lowercase=False, preprocessor=None)

In [78]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

stop = stopwords.words('english')
param_grid = [
             {'vect__ngram_range': [(1,1),(1,2),(1,3)],
              'vect__stop_words': [stop, None],
              'clf__alpha': (1e-2, 1e-3),
              'vect__use_idf': [True,False],
              'vect__norm': [None]}]

lr_tfidf = Pipeline([('vect', tfidf), ('clf',XGBClassifier(random_state=0))])

gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)

gs_lr_tfidf.fit(X_train, y_train)

print('Best parameter set: %s' % gs_lr_tfidf.best_params_)

Fitting 3 folds for each of 24 candidates, totalling 72 fits


In [ ]:
predictions = gs_lr_tfidf.predict(X_test)

In [ ]:
print(metrics.accuracy_score(y_test,predictions))

In [ ]:
print(gs_lr_tfidf.predict([text1]))
print(gs_lr_tfidf.predict([text2]))# be sure to put "text" inside square brackets
print(gs_lr_tfidf.predict([text3]))
print(gs_lr_tfidf.predict([text4]))
print(gs_lr_tfidf.predict([text5]))